### ISSUE TITLE
Allow custom activity from outside (during ExceptionReport creation) instead of ExceptionReportActivity

### ISSUE THREAD

**Issue by Enes-Kayiklik** [cnrture/ExceptionReport#1]

**Comment by cnrture** [comment]
Why do you need this?

**Comment by Enes-Kayiklik** [comment]
When we want to change ui or action buttons(click button to send Email to developer of the app etc.) i thought this was the best option to have set custom ui. If is there any oher solution for this could you provide sample?

**Comment by cnrture** [comment]
Got it, I will add support as soon as possible. I was wondering why, it just made sense :)

**Comment by Enes-Kayiklik** [comment]
I can work on it if it is okay to you

**Comment by cnrture** [comment]
I added the feature where you can use your own Activity. Thanks for the suggestion bro.
